### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by Yogeshvasu** [Vahe1994/Deep-Vectorization-of-Technical-Drawings#1]
could you please give procedure to run & generate model or could you please provide trained model for windows which could test for our images

**Comment by Vahe1994** [comment]
Hello! 
I didn't try to run the code on Windows. You can try to run Jupiter notebooks for model evaluation(I added recently) in the notebooks/ folder for your images, but I doubt the code will work on Windows. To train the new model, u can use code from vectorization/scripts/train_vectorization.py  and slightly rewrite it for your scenario. 
P.s. Frankly said the easiest solution is to run code on Linux.
