### ISSUE TITLE
RuntimeError in lines_refinement_functions.py

### ISSUE THREAD

**Issue by tabearasa** [Vahe1994/Deep-Vectorization-of-Technical-Drawings#12]
Hello and thank you for sharing the code of your paper!
I want to run your pipeline on my own adapted dataset, but I currently only run it on my internal CPU. 
In this [line](https://github.com/Vahe1994/Deep-Vectorization-of-Technical-Drawings/blob/964302647558e90f3ed5026591fb5b40f56c0ff0/refinement/our_refinement/utils/lines_refinement_functions.py#L847) from the lines_refinement_functions.py comes the following RuntimeError: 

> unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.

Comes this Error from the usage of the CPU and should I considering working with a GPU? 
Side note: (First, I want to use the already provided model weights and don't want to train again the model right now, if the results are good)

**Comment by Vahe1994** [comment]
Hello!
Thank you for your kind words. It's odd, I think the problem is your torch version and not your CPU(I will try it on CPU to make sure). What version of torch do you use ?

**Comment by tabearasa** [comment]
If I install the the listed packages in the requirements.txt I get the following error:

```
ERROR: Cannot install -r requirements.txt (line 112), -r requirements.txt (line 116), -r requirements.txt (line 52), -r requirements.txt (line 88) and torch==1.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.6.0
    kornia 0.4.1 depends on torch>=1.6.0
    pytorch-lightning 1.0.8 depends on torch>=1.3
    test-tube 0.7.5 depends on torch>=1.1.0
    torchvision 0.8.2 depends on torch==1.7.1
```

It solved an on conda environment for me, with the following versions of the conflicted packages: 

```
torch                     1.6.0                    pypi_0    pypi
torchvision               0.7.0                  py38_cpu  [cpuonly]  pytorch
```
Hope this helps!
