### ISSUE TITLE
Bad Results

### ISSUE THREAD

**Issue by Flo2204** [Vahe1994/Deep-Vectorization-of-Technical-Drawings#18]
Hello, 
First thank you for sharing your great work. I wanted to test your code for a Project and installed it on a ubuntu machine. 
The Installation works fine but I only get some images (png's) (no vector graphics) as output  and these are looking terrible ( just a few lines). I run the whole Pipeline. Do you have some Idea what I may made wrong.

Thank you,

Florian

**Comment by Vahe1994** [comment]
Hello!
Frankly speaking, it's hard to tell. If you provide more information, it would be great. I will gladly try to help find the issue. Can you please provide information about:
1) What code did you run (which file and how?)
2) Did you manage to make the code work on provided jupyter notebooks and example from those notebooks?
3) Can you please provide image(s), on which you got those bad results.
4) Your environment specification(PIL version, Pytorch version, Scikit learn version e.t.c) would be nice to have too.

As for output being png(it is easier to open), it is rendered from vector graphics. You can always save this "images" (table of bezie curves and lines) in vector graphics(svg) format, there are functions for it. If you are having trouble of finding them  , I will either commit the code into pipeline for saving or tell what functions to use to do it yourself.

With best,
Vage

**Comment by Flo2204** [comment]
Hey,

Thank you for your quick response and sorry for the late reply. 
I first tried the script run_pipeline.py. 
But in the last weeks I tried the Notebooks and changed some stuff to make it runable with my torchvision version. Now it runs. But I hat bad results, so I changed the patch size which made my results much better. Now I'm struggling with the svg export, can you provide me the right function? 
Are you still work on this software to improve it further?

Kind regards,

Florian

**Comment by Vahe1994** [comment]
Hello! Sorry for late response. I added examples of how to save to SVG at the end for curve and lines notebooks.
Please try them and tell me if you have any difficulties.
As for software improvement, if you mean code improvement-yes (I'm trying to refactor cleaning part, but unfortunately it's going slowly, because of my main work), further algorithm improvement - no.
