### ISSUE TITLE
Question about PFP dataset

### ISSUE THREAD

**Issue by chunibyo-wly** [Vahe1994/Deep-Vectorization-of-Technical-Drawings#26]
Hello, thanks for your great work.
I want to work on PFP dataset, but I found that the website of [http://www.precisionfloorplan.com/sitemap/](http://www.precisionfloorplan.com/sitemap/) was disappeared and I went to [webarchive](https://web.archive.org/web/20140214053210/http://www.precisionfloorplan.com/sitemap/) website, unfortunately they did not store pdf files.

Could please send me your dataset which you downloaded from that website?
thank.

**Comment by Vahe1994** [comment]
Hello, thank you for nice words.
Unfortunately, I don't have the dataset.
Alternatively , you can try to use ABC dataset or  dataset with 15000 floorplans from  ICCV paper https://floorplancad.github.io/.

**Comment by chunibyo-wly** [comment]
Thank you
